// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package http

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for OrganisationRoleStatus.
const (
	Active   OrganisationRoleStatus = "Active"
	Inactive OrganisationRoleStatus = "Inactive"
)

// Address defines model for Address.
type Address struct {
	City    *string `json:"city,omitempty"`
	Country *string `json:"country,omitempty"`

	// Lines Address lines, in order.
	Lines      *[]string `json:"lines,omitempty"`
	PostalCode *string   `json:"postalCode,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Code Application-specific error code.
	Code string `json:"code"`

	// Details Optional error details.
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable error message.
	Message string `json:"message"`
}

// OperationalPeriod defines model for OperationalPeriod.
type OperationalPeriod struct {
	// DateType Free-text date type (for example, 'Operational', 'Legal'), as supplied by ODS.
	DateType *string `json:"dateType"`

	// End Operational end date, if any.
	End *openapi_types.Date `json:"end"`

	// Start Operational start date (YYYY-MM-DD).
	Start openapi_types.Date `json:"start"`
}

// Organisation Simplified organisation view derived from ODS FHIR Organization.
type Organisation struct {
	Address *Address `json:"address,omitempty"`

	// Id Internal identifier (usually same as odsCode).
	Id string `json:"id"`

	// IsActive Indicates whether the organisation is operationally active at the time of the lookup.
	IsActive bool                 `json:"isActive"`
	Metadata OrganisationMetadata `json:"metadata"`

	// Name Organisation name.
	Name string `json:"name"`

	// OdsCode ODS organisation code.
	OdsCode           string             `json:"odsCode"`
	OperationalPeriod *OperationalPeriod `json:"operationalPeriod,omitempty"`

	// RecordClass ODS record class (for example, HSCOrg, HSCAS, HSCWard, HSCSubOrg).
	RecordClass string `json:"recordClass"`

	// Roles Current or historical roles assigned to the organisation.
	Roles *[]OrganisationRole `json:"roles,omitempty"`
}

// OrganisationMetadata defines model for OrganisationMetadata.
type OrganisationMetadata struct {
	// LastUpdated Last update timestamp from ODS FHIR (meta.lastUpdated).
	LastUpdated time.Time `json:"lastUpdated"`
}

// OrganisationRole defines model for OrganisationRole.
type OrganisationRole struct {
	// Code ODS role code.
	Code string `json:"code"`

	// Display Human-readable role description.
	Display           string             `json:"display"`
	OperationalPeriod *OperationalPeriod `json:"operationalPeriod,omitempty"`

	// Primary True if this is the primary role.
	Primary bool `json:"primary"`

	// Status Role status.
	Status OrganisationRoleStatus `json:"status"`
}

// OrganisationRoleStatus Role status.
type OrganisationRoleStatus string

// OrganisationSearchResponse defines model for OrganisationSearchResponse.
type OrganisationSearchResponse struct {
	// Items List of organisations for the current page.
	Items *[]Organisation `json:"items,omitempty"`

	// Page Current page number (1-based).
	Page *int `json:"page,omitempty"`

	// PageSize Page size.
	PageSize *int `json:"pageSize,omitempty"`

	// Total Total number of records matching the search criteria.
	Total int `json:"total"`
}

// SearchOrganisationsParams defines parameters for SearchOrganisations.
type SearchOrganisationsParams struct {
	// Name Case-insensitive substring match on organisation name.
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// City City / town.
	City *string `form:"city,omitempty" json:"city,omitempty"`

	// Postcode Postcode (full or prefix).
	Postcode *string `form:"postcode,omitempty" json:"postcode,omitempty"`

	// Active Filter by organisation activity status.
	Active *bool `form:"active,omitempty" json:"active,omitempty"`

	// RoleCode Filter by role code (for example, '141' for local authority, 'RO189' for GP practice).
	RoleCode *string `form:"roleCode,omitempty" json:"roleCode,omitempty"`

	// PrimaryRoleOnly If true, only organisations where the matching role is a primary role are returned.
	PrimaryRoleOnly *bool `form:"primaryRoleOnly,omitempty" json:"primaryRoleOnly,omitempty"`

	// LastUpdatedFrom Return organisations last updated on or after this date (ISO-8601 date).
	LastUpdatedFrom *openapi_types.Date `form:"lastUpdatedFrom,omitempty" json:"lastUpdatedFrom,omitempty"`

	// Page Page number (1-based).
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Page size (max 200).
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetOrganisationByOdsCodeParams defines parameters for GetOrganisationByOdsCode.
type GetOrganisationByOdsCodeParams struct {
	// IncludeInactiveRoles If true, returns both active and inactive roles. If false or omitted, only active roles are returned.
	IncludeInactiveRoles *bool `form:"includeInactiveRoles,omitempty" json:"includeInactiveRoles,omitempty"`
}
