// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package http

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetCodesystemId request
	GetCodesystemId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOrganizationResources request
	GetOrganizationResources(ctx context.Context, params *GetOrganizationResourcesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSingleOrganization request
	GetSingleOrganization(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetValuesetSpecifiedId request
	GetValuesetSpecifiedId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCapabilityStatement request
	GetCapabilityStatement(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetCodesystemId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCodesystemIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetOrganizationResources(ctx context.Context, params *GetOrganizationResourcesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOrganizationResourcesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSingleOrganization(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSingleOrganizationRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetValuesetSpecifiedId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetValuesetSpecifiedIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCapabilityStatement(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCapabilityStatementRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCodesystemIdRequest generates requests for GetCodesystemId
func NewGetCodesystemIdRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/CodeSystem/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetOrganizationResourcesRequest generates requests for GetOrganizationResources
func NewGetOrganizationResourcesRequest(server string, params *GetOrganizationResourcesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/Organization")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.UnderscoreId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "_id", runtime.ParamLocationQuery, *params.UnderscoreId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Identifier != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "identifier", runtime.ParamLocationQuery, *params.Identifier); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.UnderscoreLastUpdated != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "_lastUpdated", runtime.ParamLocationQuery, *params.UnderscoreLastUpdated); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Name != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "name", runtime.ParamLocationQuery, *params.Name); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.NameContains != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "name:contains", runtime.ParamLocationQuery, *params.NameContains); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.NameExact != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "name:exact", runtime.ParamLocationQuery, *params.NameExact); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Active != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "active", runtime.ParamLocationQuery, *params.Active); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.AddressPostalcode != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "address-postalcode", runtime.ParamLocationQuery, *params.AddressPostalcode); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.AddressPostalcodeContains != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "address-postalcode:contains", runtime.ParamLocationQuery, *params.AddressPostalcodeContains); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.AddressPostalcodeExact != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "address-postalcode:exact", runtime.ParamLocationQuery, *params.AddressPostalcodeExact); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.AddressCity != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "address-city", runtime.ParamLocationQuery, *params.AddressCity); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.AddressCityContains != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "address-city:contains", runtime.ParamLocationQuery, *params.AddressCityContains); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.AddressCityExact != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "address-city:exact", runtime.ParamLocationQuery, *params.AddressCityExact); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.OdsOrgRole != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "ods-org-role", runtime.ParamLocationQuery, *params.OdsOrgRole); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.OdsOrgPrimaryRole != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "ods-org-primaryRole", runtime.ParamLocationQuery, *params.OdsOrgPrimaryRole); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.UnderscoreCount != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "_count", runtime.ParamLocationQuery, *params.UnderscoreCount); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.UnderscoreSummary != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "_summary", runtime.ParamLocationQuery, *params.UnderscoreSummary); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSingleOrganizationRequest generates requests for GetSingleOrganization
func NewGetSingleOrganizationRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/Organization/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetValuesetSpecifiedIdRequest generates requests for GetValuesetSpecifiedId
func NewGetValuesetSpecifiedIdRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ValueSet/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCapabilityStatementRequest generates requests for GetCapabilityStatement
func NewGetCapabilityStatementRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/metadata")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetCodesystemIdWithResponse request
	GetCodesystemIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetCodesystemIdResponse, error)

	// GetOrganizationResourcesWithResponse request
	GetOrganizationResourcesWithResponse(ctx context.Context, params *GetOrganizationResourcesParams, reqEditors ...RequestEditorFn) (*GetOrganizationResourcesResponse, error)

	// GetSingleOrganizationWithResponse request
	GetSingleOrganizationWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetSingleOrganizationResponse, error)

	// GetValuesetSpecifiedIdWithResponse request
	GetValuesetSpecifiedIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetValuesetSpecifiedIdResponse, error)

	// GetCapabilityStatementWithResponse request
	GetCapabilityStatementWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCapabilityStatementResponse, error)
}

type GetCodesystemIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetCodesystemIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCodesystemIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetOrganizationResourcesResponse struct {
	Body                   []byte
	HTTPResponse           *http.Response
	ApplicationfhirJSON200 *OrganizationBundle
}

// Status returns HTTPResponse.Status
func (r GetOrganizationResourcesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOrganizationResourcesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSingleOrganizationResponse struct {
	Body                   []byte
	HTTPResponse           *http.Response
	ApplicationfhirJSON200 *OrganizationResource
}

// Status returns HTTPResponse.Status
func (r GetSingleOrganizationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSingleOrganizationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetValuesetSpecifiedIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetValuesetSpecifiedIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetValuesetSpecifiedIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCapabilityStatementResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetCapabilityStatementResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCapabilityStatementResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetCodesystemIdWithResponse request returning *GetCodesystemIdResponse
func (c *ClientWithResponses) GetCodesystemIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetCodesystemIdResponse, error) {
	rsp, err := c.GetCodesystemId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCodesystemIdResponse(rsp)
}

// GetOrganizationResourcesWithResponse request returning *GetOrganizationResourcesResponse
func (c *ClientWithResponses) GetOrganizationResourcesWithResponse(ctx context.Context, params *GetOrganizationResourcesParams, reqEditors ...RequestEditorFn) (*GetOrganizationResourcesResponse, error) {
	rsp, err := c.GetOrganizationResources(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOrganizationResourcesResponse(rsp)
}

// GetSingleOrganizationWithResponse request returning *GetSingleOrganizationResponse
func (c *ClientWithResponses) GetSingleOrganizationWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetSingleOrganizationResponse, error) {
	rsp, err := c.GetSingleOrganization(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSingleOrganizationResponse(rsp)
}

// GetValuesetSpecifiedIdWithResponse request returning *GetValuesetSpecifiedIdResponse
func (c *ClientWithResponses) GetValuesetSpecifiedIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetValuesetSpecifiedIdResponse, error) {
	rsp, err := c.GetValuesetSpecifiedId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetValuesetSpecifiedIdResponse(rsp)
}

// GetCapabilityStatementWithResponse request returning *GetCapabilityStatementResponse
func (c *ClientWithResponses) GetCapabilityStatementWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCapabilityStatementResponse, error) {
	rsp, err := c.GetCapabilityStatement(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCapabilityStatementResponse(rsp)
}

// ParseGetCodesystemIdResponse parses an HTTP response from a GetCodesystemIdWithResponse call
func ParseGetCodesystemIdResponse(rsp *http.Response) (*GetCodesystemIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCodesystemIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetOrganizationResourcesResponse parses an HTTP response from a GetOrganizationResourcesWithResponse call
func ParseGetOrganizationResourcesResponse(rsp *http.Response) (*GetOrganizationResourcesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOrganizationResourcesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OrganizationBundle
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationfhirJSON200 = &dest

	}

	return response, nil
}

// ParseGetSingleOrganizationResponse parses an HTTP response from a GetSingleOrganizationWithResponse call
func ParseGetSingleOrganizationResponse(rsp *http.Response) (*GetSingleOrganizationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSingleOrganizationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OrganizationResource
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationfhirJSON200 = &dest

	}

	return response, nil
}

// ParseGetValuesetSpecifiedIdResponse parses an HTTP response from a GetValuesetSpecifiedIdWithResponse call
func ParseGetValuesetSpecifiedIdResponse(rsp *http.Response) (*GetValuesetSpecifiedIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetValuesetSpecifiedIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetCapabilityStatementResponse parses an HTTP response from a GetCapabilityStatementWithResponse call
func ParseGetCapabilityStatementResponse(rsp *http.Response) (*GetCapabilityStatementResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCapabilityStatementResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
