// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package http

import (
	"encoding/json"
	"fmt"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for OrganizationBundleResourceType.
const (
	Bundle OrganizationBundleResourceType = "Bundle"
)

// Defines values for OrganizationResourceResourceType.
const (
	Organization OrganizationResourceResourceType = "Organization"
)

// Defines values for GetOrganizationResourcesParamsSummary.
const (
	Count GetOrganizationResourcesParamsSummary = "count"
)

// Address defines model for Address.
type Address struct {
	City       *string   `json:"city,omitempty"`
	Country    *string   `json:"country,omitempty"`
	District   *string   `json:"district,omitempty"`
	Line       *[]string `json:"line,omitempty"`
	PostalCode *string   `json:"postalCode,omitempty"`
}

// BundleLink defines model for BundleLink.
type BundleLink struct {
	Relation *string `json:"relation,omitempty"`
	Url      *string `json:"url,omitempty"`
}

// Coding defines model for Coding.
type Coding struct {
	Code    *string `json:"code,omitempty"`
	Display *string `json:"display,omitempty"`
	System  *string `json:"system,omitempty"`
}

// Extension Generic FHIR extension; for ODS this is typically ActivePeriod or OrganizationRole.
type Extension struct {
	Extension            *[]Extension           `json:"extension,omitempty"`
	Url                  *string                `json:"url,omitempty"`
	ValueBoolean         *bool                  `json:"valueBoolean,omitempty"`
	ValueCoding          *Coding                `json:"valueCoding,omitempty"`
	ValuePeriod          *Period                `json:"valuePeriod,omitempty"`
	ValueString          *string                `json:"valueString,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Identifier defines model for Identifier.
type Identifier struct {
	System *string `json:"system,omitempty"`
	Value  *string `json:"value,omitempty"`
}

// Meta defines model for Meta.
type Meta struct {
	LastUpdated *time.Time `json:"lastUpdated,omitempty"`
	Profile     *string    `json:"profile,omitempty"`
}

// OrganizationBundle FHIR Bundle of Organization resources returned by the ODS API.
type OrganizationBundle struct {
	Entry        *[]OrganizationEntry           `json:"entry,omitempty"`
	Id           *string                        `json:"id,omitempty"`
	Link         *[]BundleLink                  `json:"link,omitempty"`
	Meta         *Meta                          `json:"meta,omitempty"`
	ResourceType OrganizationBundleResourceType `json:"resourceType"`

	// Total Total number of matching resources.
	Total *string `json:"total,omitempty"`

	// Type Bundle type (for ODS, usually 'searchset').
	Type string `json:"type"`
}

// OrganizationBundleResourceType defines model for OrganizationBundle.ResourceType.
type OrganizationBundleResourceType string

// OrganizationEntry defines model for OrganizationEntry.
type OrganizationEntry struct {
	FullUrl *string `json:"fullUrl,omitempty"`

	// Resource FHIR Organization resource (ODS profile).
	Resource *OrganizationResource `json:"resource,omitempty"`
}

// OrganizationResource FHIR Organization resource (ODS profile).
type OrganizationResource struct {
	Active       *bool                            `json:"active,omitempty"`
	Address      *Address                         `json:"address,omitempty"`
	Extension    *[]Extension                     `json:"extension,omitempty"`
	Id           string                           `json:"id"`
	Identifier   *Identifier                      `json:"identifier,omitempty"`
	Meta         *Meta                            `json:"meta,omitempty"`
	Name         string                           `json:"name"`
	ResourceType OrganizationResourceResourceType `json:"resourceType"`
	Type         *struct {
		Coding *Coding `json:"coding,omitempty"`
	} `json:"type,omitempty"`
}

// OrganizationResourceResourceType defines model for OrganizationResource.ResourceType.
type OrganizationResourceResourceType string

// Period defines model for Period.
type Period struct {
	End       *openapi_types.Date `json:"end"`
	Extension *[]Extension        `json:"extension,omitempty"`
	Start     *openapi_types.Date `json:"start,omitempty"`
}

// GetOrganizationResourcesParams defines parameters for GetOrganizationResources.
type GetOrganizationResourcesParams struct {
	// UnderscoreId The organisation's ID - also known as its ODS code. If you already know the ODS code, consider using the 'Get organsiation details' endpoint instead.
	UnderscoreId *string `form:"_id,omitempty" json:"_id,omitempty"`

	// Identifier The organisation's ID - also known as its ODS code.
	// This parameter is similar to `_id` but can also explicitly include the code system for the ID - which must be `ods-organization-code`.
	// It's included for FHIR compatibility.
	Identifier *string `form:"identifier,omitempty" json:"identifier,omitempty"`

	// UnderscoreLastUpdated The date that the organisation was last updated. Only supports matching of updates that happened after the given date, using the prefix `gt` (greater than).
	UnderscoreLastUpdated *string `form:"_lastUpdated,omitempty" json:"_lastUpdated,omitempty"`

	// Name The start of the organisation's name. For example, `Leeds` would match 'Leeds Chest Clinic' but not 'South Leeds Clinical Assessment Service'.
	//
	// To search anywhere in the organisation's name, use `name:contains`. To search for an exact match, use `name:exact`.
	//
	// Not case sensitive.
	//
	// Search expressions must:
	// - contain a minimum of 3 characters and a maximum of 100 characters
	// - only include the following characters: A-Z a-z 0-9 &()â+-_./:@ 'Space'
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// NameContains Any part of the organisation's name. For example, `Leeds` would match 'Leeds Chest Clinic' and 'South Leeds Clinical Assessment Service'.
	//
	// Not case sensitive.
	//
	// Search expressions must:
	// - contain a minimum of 3 characters and a maximum of 100 characters
	// - only include the following characters: A-Z a-z 0-9 &()â+-_./:@ 'Space'
	NameContains *string `form:"name:contains,omitempty" json:"name:contains,omitempty"`

	// NameExact The exact organisation name.
	//
	// Case sensitive.
	//
	// Search expressions must:
	// - contain a minimum of 3 characters and a maximum of 100 characters
	// - only include the following characters: A-Z a-z 0-9 &()â+-_./:@ 'Space'
	NameExact *string `form:"name:exact,omitempty" json:"name:exact,omitempty"`

	// Active Whether the organisation's record is still in active use.
	Active *bool `form:"active,omitempty" json:"active,omitempty"`

	// AddressPostalcode The start of the organisation's postcode.
	//
	// To search anywhere in the postcode, use `address-postalcode:contains`. To search for an exact match, use `address-postalcode:exact`.
	//
	// Not case sensitive.
	//
	// Search expressions must:
	// - contain a minimum of 2 characters
	// - only include alphanumeric characters and spaces
	AddressPostalcode *string `form:"address-postalcode,omitempty" json:"address-postalcode,omitempty"`

	// AddressPostalcodeContains Any part of the organisation's postcode.
	//
	// Not case sensitive.
	//
	// Search expressions must:
	// - contain a minimum of 2 characters
	// - only include alphanumeric characters and spaces
	AddressPostalcodeContains *string `form:"address-postalcode:contains,omitempty" json:"address-postalcode:contains,omitempty"`

	// AddressPostalcodeExact The exact organisation postcode.
	//
	// Case sensitive.
	//
	// Search expressions must:
	// - contain a minimum of 2 characters
	// - only include alphanumeric characters and spaces
	AddressPostalcodeExact *string `form:"address-postalcode:exact,omitempty" json:"address-postalcode:exact,omitempty"`

	// AddressCity The start of the organisation's city address.
	//
	// To search anywhere in the city address, use `address-city:contains`. To search for an exact match, use `address-city:exact`.
	//
	// Not case sensitive.
	//
	// Search expressions must:
	// - contain a minimum of 2 characters
	// - only include alphanumeric characters and spaces
	AddressCity *string `form:"address-city,omitempty" json:"address-city,omitempty"`

	// AddressCityContains Any part of the organisation's city address.
	//
	// Not case sensitive.
	//
	// Search expressions must:
	// - contain a minimum of 2 characters
	// - only include alphanumeric characters and spaces
	AddressCityContains *string `form:"address-city:contains,omitempty" json:"address-city:contains,omitempty"`

	// AddressCityExact The exact organisation city address.
	//
	// Case sensitive.
	//
	// Search expressions must:
	// - contain a minimum of 2 characters
	// - only include alphanumeric characters and spaces
	AddressCityExact *string `form:"address-city:exact,omitempty" json:"address-city:exact,omitempty"`

	// OdsOrgRole The organisation's role, based on the ODS organisation role code system.
	//
	// An organisation in ODS can have one or many roles.
	//
	// To search for organisations that have multiple roles (like an 'AND' operator), include the `ods-org-role` query parameter multiple times. For example:
	//
	// `GET https://directory.spineservices.nhs.uk/STU3/Organization?ods-org-role=76&ods-org-role=177`
	//
	// To search for organisations that have one of several roles (like an 'OR' operator), use a comma separator. For example:
	//
	// `GET https://directory.spineservices.nhs.uk/STU3/Organization?ods-org-role=197,198`
	//
	// You may combine 'AND' and 'OR' searches.
	OdsOrgRole *string `form:"ods-org-role,omitempty" json:"ods-org-role,omitempty"`

	// OdsOrgPrimaryRole Whether a role of the organisation is its primary role. Must be used in conjunction with the `ods-org-role` parameter.
	OdsOrgPrimaryRole *bool `form:"ods-org-primaryRole,omitempty" json:"ods-org-primaryRole,omitempty"`

	// UnderscoreCount Number of results to return. Defaulted to first 20 records.
	UnderscoreCount *string `form:"_count,omitempty" json:"_count,omitempty"`

	// UnderscorePage Page number. Default 1
	UnderscorePage *string `form:"_page,omitempty" json:"_page,omitempty"`

	// UnderscoreSummary Return a count of the matching resources, without returning the actual matches.
	UnderscoreSummary *GetOrganizationResourcesParamsSummary `form:"_summary,omitempty" json:"_summary,omitempty"`
}

// GetOrganizationResourcesParamsSummary defines parameters for GetOrganizationResources.
type GetOrganizationResourcesParamsSummary string

// Getter for additional properties for Extension. Returns the specified
// element and whether it was found
func (a Extension) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Extension
func (a *Extension) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Extension to handle AdditionalProperties
func (a *Extension) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["extension"]; found {
		err = json.Unmarshal(raw, &a.Extension)
		if err != nil {
			return fmt.Errorf("error reading 'extension': %w", err)
		}
		delete(object, "extension")
	}

	if raw, found := object["url"]; found {
		err = json.Unmarshal(raw, &a.Url)
		if err != nil {
			return fmt.Errorf("error reading 'url': %w", err)
		}
		delete(object, "url")
	}

	if raw, found := object["valueBoolean"]; found {
		err = json.Unmarshal(raw, &a.ValueBoolean)
		if err != nil {
			return fmt.Errorf("error reading 'valueBoolean': %w", err)
		}
		delete(object, "valueBoolean")
	}

	if raw, found := object["valueCoding"]; found {
		err = json.Unmarshal(raw, &a.ValueCoding)
		if err != nil {
			return fmt.Errorf("error reading 'valueCoding': %w", err)
		}
		delete(object, "valueCoding")
	}

	if raw, found := object["valuePeriod"]; found {
		err = json.Unmarshal(raw, &a.ValuePeriod)
		if err != nil {
			return fmt.Errorf("error reading 'valuePeriod': %w", err)
		}
		delete(object, "valuePeriod")
	}

	if raw, found := object["valueString"]; found {
		err = json.Unmarshal(raw, &a.ValueString)
		if err != nil {
			return fmt.Errorf("error reading 'valueString': %w", err)
		}
		delete(object, "valueString")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Extension to handle AdditionalProperties
func (a Extension) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Extension != nil {
		object["extension"], err = json.Marshal(a.Extension)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'extension': %w", err)
		}
	}

	if a.Url != nil {
		object["url"], err = json.Marshal(a.Url)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'url': %w", err)
		}
	}

	if a.ValueBoolean != nil {
		object["valueBoolean"], err = json.Marshal(a.ValueBoolean)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'valueBoolean': %w", err)
		}
	}

	if a.ValueCoding != nil {
		object["valueCoding"], err = json.Marshal(a.ValueCoding)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'valueCoding': %w", err)
		}
	}

	if a.ValuePeriod != nil {
		object["valuePeriod"], err = json.Marshal(a.ValuePeriod)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'valuePeriod': %w", err)
		}
	}

	if a.ValueString != nil {
		object["valueString"], err = json.Marshal(a.ValueString)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'valueString': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
