// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/Cleo-Systems/ods-fhir-gateway/internal/service/ods-gateway/app/common"
	http "github.com/Cleo-Systems/ods-fhir-gateway/pkg/ods-fhir-api/client"
)

type FakeOdsFHIRClient struct {
	GetOrganisationByIDStub        func(context.Context, string) (*http.OrganizationResource, error)
	getOrganisationByIDMutex       sync.RWMutex
	getOrganisationByIDArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getOrganisationByIDReturns struct {
		result1 *http.OrganizationResource
		result2 error
	}
	getOrganisationByIDReturnsOnCall map[int]struct {
		result1 *http.OrganizationResource
		result2 error
	}
	SearchOrganisationsStub        func(context.Context, common.SeachOrganisationsRequest) (*http.OrganizationBundle, error)
	searchOrganisationsMutex       sync.RWMutex
	searchOrganisationsArgsForCall []struct {
		arg1 context.Context
		arg2 common.SeachOrganisationsRequest
	}
	searchOrganisationsReturns struct {
		result1 *http.OrganizationBundle
		result2 error
	}
	searchOrganisationsReturnsOnCall map[int]struct {
		result1 *http.OrganizationBundle
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeOdsFHIRClient) GetOrganisationByID(arg1 context.Context, arg2 string) (*http.OrganizationResource, error) {
	fake.getOrganisationByIDMutex.Lock()
	ret, specificReturn := fake.getOrganisationByIDReturnsOnCall[len(fake.getOrganisationByIDArgsForCall)]
	fake.getOrganisationByIDArgsForCall = append(fake.getOrganisationByIDArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetOrganisationByIDStub
	fakeReturns := fake.getOrganisationByIDReturns
	fake.recordInvocation("GetOrganisationByID", []interface{}{arg1, arg2})
	fake.getOrganisationByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeOdsFHIRClient) GetOrganisationByIDCallCount() int {
	fake.getOrganisationByIDMutex.RLock()
	defer fake.getOrganisationByIDMutex.RUnlock()
	return len(fake.getOrganisationByIDArgsForCall)
}

func (fake *FakeOdsFHIRClient) GetOrganisationByIDCalls(stub func(context.Context, string) (*http.OrganizationResource, error)) {
	fake.getOrganisationByIDMutex.Lock()
	defer fake.getOrganisationByIDMutex.Unlock()
	fake.GetOrganisationByIDStub = stub
}

func (fake *FakeOdsFHIRClient) GetOrganisationByIDArgsForCall(i int) (context.Context, string) {
	fake.getOrganisationByIDMutex.RLock()
	defer fake.getOrganisationByIDMutex.RUnlock()
	argsForCall := fake.getOrganisationByIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeOdsFHIRClient) GetOrganisationByIDReturns(result1 *http.OrganizationResource, result2 error) {
	fake.getOrganisationByIDMutex.Lock()
	defer fake.getOrganisationByIDMutex.Unlock()
	fake.GetOrganisationByIDStub = nil
	fake.getOrganisationByIDReturns = struct {
		result1 *http.OrganizationResource
		result2 error
	}{result1, result2}
}

func (fake *FakeOdsFHIRClient) GetOrganisationByIDReturnsOnCall(i int, result1 *http.OrganizationResource, result2 error) {
	fake.getOrganisationByIDMutex.Lock()
	defer fake.getOrganisationByIDMutex.Unlock()
	fake.GetOrganisationByIDStub = nil
	if fake.getOrganisationByIDReturnsOnCall == nil {
		fake.getOrganisationByIDReturnsOnCall = make(map[int]struct {
			result1 *http.OrganizationResource
			result2 error
		})
	}
	fake.getOrganisationByIDReturnsOnCall[i] = struct {
		result1 *http.OrganizationResource
		result2 error
	}{result1, result2}
}

func (fake *FakeOdsFHIRClient) SearchOrganisations(arg1 context.Context, arg2 common.SeachOrganisationsRequest) (*http.OrganizationBundle, error) {
	fake.searchOrganisationsMutex.Lock()
	ret, specificReturn := fake.searchOrganisationsReturnsOnCall[len(fake.searchOrganisationsArgsForCall)]
	fake.searchOrganisationsArgsForCall = append(fake.searchOrganisationsArgsForCall, struct {
		arg1 context.Context
		arg2 common.SeachOrganisationsRequest
	}{arg1, arg2})
	stub := fake.SearchOrganisationsStub
	fakeReturns := fake.searchOrganisationsReturns
	fake.recordInvocation("SearchOrganisations", []interface{}{arg1, arg2})
	fake.searchOrganisationsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeOdsFHIRClient) SearchOrganisationsCallCount() int {
	fake.searchOrganisationsMutex.RLock()
	defer fake.searchOrganisationsMutex.RUnlock()
	return len(fake.searchOrganisationsArgsForCall)
}

func (fake *FakeOdsFHIRClient) SearchOrganisationsCalls(stub func(context.Context, common.SeachOrganisationsRequest) (*http.OrganizationBundle, error)) {
	fake.searchOrganisationsMutex.Lock()
	defer fake.searchOrganisationsMutex.Unlock()
	fake.SearchOrganisationsStub = stub
}

func (fake *FakeOdsFHIRClient) SearchOrganisationsArgsForCall(i int) (context.Context, common.SeachOrganisationsRequest) {
	fake.searchOrganisationsMutex.RLock()
	defer fake.searchOrganisationsMutex.RUnlock()
	argsForCall := fake.searchOrganisationsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeOdsFHIRClient) SearchOrganisationsReturns(result1 *http.OrganizationBundle, result2 error) {
	fake.searchOrganisationsMutex.Lock()
	defer fake.searchOrganisationsMutex.Unlock()
	fake.SearchOrganisationsStub = nil
	fake.searchOrganisationsReturns = struct {
		result1 *http.OrganizationBundle
		result2 error
	}{result1, result2}
}

func (fake *FakeOdsFHIRClient) SearchOrganisationsReturnsOnCall(i int, result1 *http.OrganizationBundle, result2 error) {
	fake.searchOrganisationsMutex.Lock()
	defer fake.searchOrganisationsMutex.Unlock()
	fake.SearchOrganisationsStub = nil
	if fake.searchOrganisationsReturnsOnCall == nil {
		fake.searchOrganisationsReturnsOnCall = make(map[int]struct {
			result1 *http.OrganizationBundle
			result2 error
		})
	}
	fake.searchOrganisationsReturnsOnCall[i] = struct {
		result1 *http.OrganizationBundle
		result2 error
	}{result1, result2}
}

func (fake *FakeOdsFHIRClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeOdsFHIRClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ common.OdsFHIRClient = new(FakeOdsFHIRClient)
