// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for OrganisationRoleStatus.
const (
	Active   OrganisationRoleStatus = "Active"
	Inactive OrganisationRoleStatus = "Inactive"
)

// Address defines model for Address.
type Address struct {
	City    *string `json:"city,omitempty"`
	Country *string `json:"country,omitempty"`

	// Lines Address lines, in order.
	Lines      *[]string `json:"lines,omitempty"`
	PostalCode *string   `json:"postalCode,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Code Application-specific error code.
	Code string `json:"code"`

	// Details Optional error details.
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable error message.
	Message string `json:"message"`
}

// OperationalPeriod defines model for OperationalPeriod.
type OperationalPeriod struct {
	// DateType Free-text date type (for example, 'Operational', 'Legal'), as supplied by ODS.
	DateType *string `json:"dateType"`

	// End Operational end date, if any.
	End *openapi_types.Date `json:"end"`

	// Start Operational start date (YYYY-MM-DD).
	Start openapi_types.Date `json:"start"`
}

// Organisation Simplified organisation view derived from ODS FHIR Organization.
type Organisation struct {
	Address *Address `json:"address,omitempty"`

	// Id Internal identifier (usually same as odsCode).
	Id string `json:"id"`

	// IsActive Indicates whether the organisation is operationally active at the time of the lookup.
	IsActive bool                 `json:"isActive"`
	Metadata OrganisationMetadata `json:"metadata"`

	// Name Organisation name.
	Name string `json:"name"`

	// OdsCode ODS organisation code.
	OdsCode           string             `json:"odsCode"`
	OperationalPeriod *OperationalPeriod `json:"operationalPeriod,omitempty"`

	// RecordClass ODS record class (for example, HSCOrg, HSCAS, HSCWard, HSCSubOrg).
	RecordClass string `json:"recordClass"`

	// Roles Current or historical roles assigned to the organisation.
	Roles *[]OrganisationRole `json:"roles,omitempty"`
}

// OrganisationMetadata defines model for OrganisationMetadata.
type OrganisationMetadata struct {
	// LastUpdated Last update timestamp from ODS FHIR (meta.lastUpdated).
	LastUpdated time.Time `json:"lastUpdated"`
}

// OrganisationRole defines model for OrganisationRole.
type OrganisationRole struct {
	// Code ODS role code.
	Code string `json:"code"`

	// Display Human-readable role description.
	Display           string             `json:"display"`
	OperationalPeriod *OperationalPeriod `json:"operationalPeriod,omitempty"`

	// Primary True if this is the primary role.
	Primary bool `json:"primary"`

	// Status Role status.
	Status OrganisationRoleStatus `json:"status"`
}

// OrganisationRoleStatus Role status.
type OrganisationRoleStatus string

// OrganisationSearchResponse defines model for OrganisationSearchResponse.
type OrganisationSearchResponse struct {
	// Items List of organisations for the current page.
	Items *[]Organisation `json:"items,omitempty"`

	// Page Current page number (1-based).
	Page *int `json:"page,omitempty"`

	// PageSize Page size.
	PageSize *int `json:"pageSize,omitempty"`

	// Total Total number of records matching the search criteria.
	Total int `json:"total"`
}

// SearchOrganisationsParams defines parameters for SearchOrganisations.
type SearchOrganisationsParams struct {
	// Name Case-insensitive substring match on organisation name.
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// City City / town.
	City *string `form:"city,omitempty" json:"city,omitempty"`

	// Postcode Postcode (full or prefix).
	Postcode *string `form:"postcode,omitempty" json:"postcode,omitempty"`

	// Active Filter by organisation activity status.
	Active *bool `form:"active,omitempty" json:"active,omitempty"`

	// RoleCode Filter by role code (for example, '141' for local authority, 'RO189' for GP practice).
	RoleCode *string `form:"roleCode,omitempty" json:"roleCode,omitempty"`

	// PrimaryRoleOnly If true, only organisations where the matching role is a primary role are returned.
	PrimaryRoleOnly *bool `form:"primaryRoleOnly,omitempty" json:"primaryRoleOnly,omitempty"`

	// LastUpdatedFrom Return organisations last updated on or after this date (ISO-8601 date).
	LastUpdatedFrom *openapi_types.Date `form:"lastUpdatedFrom,omitempty" json:"lastUpdatedFrom,omitempty"`

	// Page Page number (1-based).
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Page size (max 200).
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetOrganisationByOdsCodeParams defines parameters for GetOrganisationByOdsCode.
type GetOrganisationByOdsCodeParams struct {
	// IncludeInactiveRoles If true, returns both active and inactive roles. If false or omitted, only active roles are returned.
	IncludeInactiveRoles *bool `form:"includeInactiveRoles,omitempty" json:"includeInactiveRoles,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// SearchOrganisations request
	SearchOrganisations(ctx context.Context, params *SearchOrganisationsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOrganisationByOdsCode request
	GetOrganisationByOdsCode(ctx context.Context, odsCode string, params *GetOrganisationByOdsCodeParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) SearchOrganisations(ctx context.Context, params *SearchOrganisationsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchOrganisationsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetOrganisationByOdsCode(ctx context.Context, odsCode string, params *GetOrganisationByOdsCodeParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOrganisationByOdsCodeRequest(c.Server, odsCode, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewSearchOrganisationsRequest generates requests for SearchOrganisations
func NewSearchOrganisationsRequest(server string, params *SearchOrganisationsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organisations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Name != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "name", runtime.ParamLocationQuery, *params.Name); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.City != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "city", runtime.ParamLocationQuery, *params.City); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Postcode != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "postcode", runtime.ParamLocationQuery, *params.Postcode); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Active != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "active", runtime.ParamLocationQuery, *params.Active); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.RoleCode != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "roleCode", runtime.ParamLocationQuery, *params.RoleCode); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PrimaryRoleOnly != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "primaryRoleOnly", runtime.ParamLocationQuery, *params.PrimaryRoleOnly); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.LastUpdatedFrom != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "lastUpdatedFrom", runtime.ParamLocationQuery, *params.LastUpdatedFrom); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "pageSize", runtime.ParamLocationQuery, *params.PageSize); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetOrganisationByOdsCodeRequest generates requests for GetOrganisationByOdsCode
func NewGetOrganisationByOdsCodeRequest(server string, odsCode string, params *GetOrganisationByOdsCodeParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "odsCode", runtime.ParamLocationPath, odsCode)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organisations/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.IncludeInactiveRoles != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "includeInactiveRoles", runtime.ParamLocationQuery, *params.IncludeInactiveRoles); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// SearchOrganisationsWithResponse request
	SearchOrganisationsWithResponse(ctx context.Context, params *SearchOrganisationsParams, reqEditors ...RequestEditorFn) (*SearchOrganisationsResponse, error)

	// GetOrganisationByOdsCodeWithResponse request
	GetOrganisationByOdsCodeWithResponse(ctx context.Context, odsCode string, params *GetOrganisationByOdsCodeParams, reqEditors ...RequestEditorFn) (*GetOrganisationByOdsCodeResponse, error)
}

type SearchOrganisationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OrganisationSearchResponse
	JSON400      *Error
	JSON500      *Error
	JSON502      *Error
}

// Status returns HTTPResponse.Status
func (r SearchOrganisationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchOrganisationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetOrganisationByOdsCodeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Organisation
	JSON404      *Error
	JSON500      *Error
	JSON502      *Error
}

// Status returns HTTPResponse.Status
func (r GetOrganisationByOdsCodeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOrganisationByOdsCodeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// SearchOrganisationsWithResponse request returning *SearchOrganisationsResponse
func (c *ClientWithResponses) SearchOrganisationsWithResponse(ctx context.Context, params *SearchOrganisationsParams, reqEditors ...RequestEditorFn) (*SearchOrganisationsResponse, error) {
	rsp, err := c.SearchOrganisations(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchOrganisationsResponse(rsp)
}

// GetOrganisationByOdsCodeWithResponse request returning *GetOrganisationByOdsCodeResponse
func (c *ClientWithResponses) GetOrganisationByOdsCodeWithResponse(ctx context.Context, odsCode string, params *GetOrganisationByOdsCodeParams, reqEditors ...RequestEditorFn) (*GetOrganisationByOdsCodeResponse, error) {
	rsp, err := c.GetOrganisationByOdsCode(ctx, odsCode, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOrganisationByOdsCodeResponse(rsp)
}

// ParseSearchOrganisationsResponse parses an HTTP response from a SearchOrganisationsWithResponse call
func ParseSearchOrganisationsResponse(rsp *http.Response) (*SearchOrganisationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchOrganisationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OrganisationSearchResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseGetOrganisationByOdsCodeResponse parses an HTTP response from a GetOrganisationByOdsCodeWithResponse call
func ParseGetOrganisationByOdsCodeResponse(rsp *http.Response) (*GetOrganisationByOdsCodeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOrganisationByOdsCodeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Organisation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Search organisations
	// (GET /organisations)
	SearchOrganisations(ctx echo.Context, params SearchOrganisationsParams) error
	// Get organisation by ODS code
	// (GET /organisations/{odsCode})
	GetOrganisationByOdsCode(ctx echo.Context, odsCode string, params GetOrganisationByOdsCodeParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// SearchOrganisations converts echo context to params.
func (w *ServerInterfaceWrapper) SearchOrganisations(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchOrganisationsParams
	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", ctx.QueryParams(), &params.Name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// ------------- Optional query parameter "city" -------------

	err = runtime.BindQueryParameter("form", true, false, "city", ctx.QueryParams(), &params.City)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter city: %s", err))
	}

	// ------------- Optional query parameter "postcode" -------------

	err = runtime.BindQueryParameter("form", true, false, "postcode", ctx.QueryParams(), &params.Postcode)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter postcode: %s", err))
	}

	// ------------- Optional query parameter "active" -------------

	err = runtime.BindQueryParameter("form", true, false, "active", ctx.QueryParams(), &params.Active)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter active: %s", err))
	}

	// ------------- Optional query parameter "roleCode" -------------

	err = runtime.BindQueryParameter("form", true, false, "roleCode", ctx.QueryParams(), &params.RoleCode)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter roleCode: %s", err))
	}

	// ------------- Optional query parameter "primaryRoleOnly" -------------

	err = runtime.BindQueryParameter("form", true, false, "primaryRoleOnly", ctx.QueryParams(), &params.PrimaryRoleOnly)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter primaryRoleOnly: %s", err))
	}

	// ------------- Optional query parameter "lastUpdatedFrom" -------------

	err = runtime.BindQueryParameter("form", true, false, "lastUpdatedFrom", ctx.QueryParams(), &params.LastUpdatedFrom)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter lastUpdatedFrom: %s", err))
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", ctx.QueryParams(), &params.PageSize)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pageSize: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchOrganisations(ctx, params)
	return err
}

// GetOrganisationByOdsCode converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganisationByOdsCode(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "odsCode" -------------
	var odsCode string

	err = runtime.BindStyledParameterWithOptions("simple", "odsCode", ctx.Param("odsCode"), &odsCode, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter odsCode: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOrganisationByOdsCodeParams
	// ------------- Optional query parameter "includeInactiveRoles" -------------

	err = runtime.BindQueryParameter("form", true, false, "includeInactiveRoles", ctx.QueryParams(), &params.IncludeInactiveRoles)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter includeInactiveRoles: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrganisationByOdsCode(ctx, odsCode, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/organisations", wrapper.SearchOrganisations)
	router.GET(baseURL+"/organisations/:odsCode", wrapper.GetOrganisationByOdsCode)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZ727juBF/FUItkASQbcnOXXf9zXWyGwPJObC9V6TboGDEkc07itSRVBLvIs/TB+mL",
	"FSQlWZKZxDns3pceECBWQs0M589vfjP+GiQiywUHrlUw/hqoZAMZth8nhEhQ9mMuRQ5SU7BPCdVb8xse",
	"cZYzCMbBJQBRQRjobW4elZaUr4OnMEhEwbXsnD7na4Y58Z1nlDsdBFQiaa6p4MG4MgXZf4eIciQkAdkP",
	"wp3Yz8F09vNsii4ml5dBGEwnlz+fLy7Pb9BytTg/XwW3YUA1ZFb6nt7yD1hKvDXPuVAas6kg0LnoMkbx",
	"p8W+6TsZ4u4XSLQRci6lkB73lVI7V8xzRhNsnnoqh4SmNEFgJCDzQuuqwadrc6nJ1b/PF4v5wudIAhpT",
	"ZvVhQqgRi9l1ww4tCwg7Nsxzd67UW8roB567ZaAUXnvucVFkmPckYILvGJSSytPtS3zAlAFBWqAEM4bm",
	"Z0v04WK2QJPrmde/En4rqARiQm19uLPi1mPhPAeJy3uDpILsR4JgDSv7XvcWHyRAT8OjRuYMMsLRcSok",
	"Ks0P0VFD/lGIji5hjdnRSYiwQqowwQSC7rbmWv1/8dbFG28GYcALxoyrqpDshRI42TewIQMBJ9bMENEU",
	"Yb5tu3kYxaNeNOqN4iAMUiEzrIOxvfohypXGUr+s3h5xfjq+ubm56V1d9c7OTtpWxO/fRb0o7kU+K16O",
	"tTPBG2K5xpwq7Izq2rikWc5oauIgGgfRPYUHREDSeyAolSLbpZ4T+MWeM/a30wXvAPGvEtJgHPxlsEPP",
	"QQmdgwo3n8KAeiI34xqk8RslwLWxT6LjQhWYsS1SOAOTQYIoAz4dJw7joa/WqZokmt6DTxcxmAIKPWxA",
	"b0AivYG2N6hCYhdMtkXYykJY27OaZoBEaj8zIX4tcpfNpRF3QjDA3CGCxgRr/Jp7mkG7qt55CgOOM88N",
	"mqeROdL2iG08aEr1Fk1FwRPKfA4qvemRfrZse2Mfap/xufChy4vX3nvBpnkiJJkyrJTfOHcAJeZEB4Au",
	"ltO5XNvfk6X99Q8sif2wLO7mcn3SxR33hu82UjBf250WUgLXSEi0oUoLSRPMkD2MsFJ0zR1+d5PKeLDu",
	"tYfmwkIw2G/FHSyghjVU4Sxzpu3GRjk0cvI19LhqJG+76BlW+lNugMpTy5dYaVTkrkfQDJTGWd7BlGNj",
	"RL8hplvU0TDqRae9aLSKorH9+WcXI3tG+KtA2TT1tQtbbx9ITWwiCgae6ohPYy/7oCpnePsqO7BSGyc6",
	"xT2fTi7R5NPqYr6YrW6+XxnmkmZYesxdyQJMU9UbqgxSmkQvD1vb+14kVBrrwlNOxufI/dNelBeZCVud",
	"rTPusLcRvJfpT+Xm3Q1q5a/FfwlYJpsFqFxw5cmEunw7CU+VNu2gWe0KGVwyrklKvMhLrvdmDPBScS/N",
	"nDZUIV5kd6aLxr07rLoFFtciKdewBlkJXdIvHsHXRqCiX9qJ/kPkk6KFxsyTNebPlVEiLUFcoQzrZEP5",
	"2vpK2QCgRFINkuK2ycPRvrpOCjjd+2E25yhPxTN8CFCK//sfTACJ+5IO/HSxbJHvEMFjLpQxFKPEJDWQ",
	"XpG3G2UmCDD0QPWm6gecoJIgoZRhrcE0B8q1QBgpzAGdreYld6Da8eCzJWr1949YwwPelhPAPUjlLI/7",
	"UT8qy53jnAbjYNSP+iOT+FhvbIoNWilp/rIGD3F1ed/J36K8rCruFNj8zrHEGWiQJmp5bigkLxtd7apB",
	"ky1W8QROckG5djet4WlGat3zlp3mBpWqYPx5L82xgh7lCriilpYZEy0muGxCgrfjYimS1U3N+78VYFHB",
	"kauqX7rS8wzCT+GeAYZaDZAWD66re4TadcCbhF4LpQ2EoeO0YMzQi1xCSh9PnlORly+8Tc0HyjRIM4S1",
	"XGRB1lxrB8U+nbiC5T2NNdS/pLJumN25MT6NjyxiMmHYFC70RkiqtyE6Wszjd+/dPz9eo1waExI4eT6e",
	"Rsn0zX6ZpchOe0hwtu2UwsMGJNg8r9HK3oQqhFutD2EJSIIuJAfyvIXlK6b1zTlr5wmBFBdMB+MUMwXh",
	"Ae5dWH0dk9mOhBFXDwin2oIbVeVcOlvOe+9+jGL7+IJDGxTqgxRZy9xXp1ZvK/H1Jq+jTJvzeicOg4xy",
	"mhm2EPv6wrMtDB1n+BENo+hFrbYPejWbrpfhR6d6GEWvGHJrOpQjFBaAh1HkSCXXwC0W492Sa/CLckN7",
	"WRmqtWj7Gqgic5ysRVtUhbMSlDExDO4xK6DBWD635nS3qqz3k/U6srGDLFeOB6wPm0vBehNYTvnlnLgb",
	"xd0+pTkUtyYJP+2vx2D/YFvPsaU2L/vdLbU6iya7R+IFY/VWp7mV6U6ju2mxHA4/V+NBSfprju/h6d/Y",
	"sJqfO6dW/Lpizk+3pgbqqDtJNiiL+OKtQTntxUbzKh6OR6fjH37cD8oKsAPGC6FyqjFTlkKtZKF0K0hO",
	"+zfwxfvYZsohQbo1Vegoc9ykucOarcbDkSWJu3o/lJ13ZgYrxcuuXHHaDdjpQRhwmC1un+5RO+P3mFFS",
	"YUODUT2FwQ9/hAWfODzmkJgOBO6MUTz8AxTnSkvAWYvBVzaYKNcw6mO+9kibOQ++lgn81ODQbR77EXQz",
	"Lf6+ndcLmRfJrHfb1qFHw3gYokV8EaLJu1EUvTupGpch+ru+tVsB7WaiEhx+Bw9yNEahO6E39f6Tm+ml",
	"fLDV1UezFFmqYiiGyKjWQEoS1Tx3IDOiPGEFgWroX9gCfhM9+k791tt66jb7Z3P9P2uuYW3a6G8ty67O",
	"V4v59fxytpr8hM5my9ViNl19C/vcN1anXfvKMvB0/9/Xznxw2lpHpKLgxDWx0++P5O1vOoTeqf+zgzlg",
	"+gi63T/c16u2jTjJCuS9v/dcS0GKxD6EQSFZMA42WudqPBgIonprt3nqb0Uhicgw5X2+Uf3i18DTNszA",
	"4zL4JVk9yrVP3u3T/wIAAP//mrKc/nQhAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
